name: Release - Deploy & Versionamento

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-sprint*"

permissions:
  contents: write

jobs:
  create-release:
    name: Publicar Release no GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gerar Release com Changelog Automatico
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref, '-sprint') || contains(github.ref, '-rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
